# Generated by Django 4.2.7 on 2023-12-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_social_alter_category_options_alter_news_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка'),
        ),
    ]
